/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.etan.portal.integration.projectservice.model.impl;

import aQute.bnd.annotation.ProviderType;
import org.etan.portal.integration.projectservice.model.InfrastructureEntityProject;
import org.etan.portal.integration.projectservice.service.InfrastructureEntityProjectLocalServiceUtil;

/**
 * The extended model base implementation for the InfrastructureEntityProject service. Represents a row in the &quot;ProjectService_InfrastructureEntityProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InfrastructureEntityProjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InfrastructureEntityProjectImpl
 * @see InfrastructureEntityProject
 * @generated
 */
@ProviderType
public abstract class InfrastructureEntityProjectBaseImpl
        extends InfrastructureEntityProjectModelImpl
        implements InfrastructureEntityProject {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a infrastructure entity project model instance should use the {@link InfrastructureEntityProject} interface instead.
     */
    @Override
    public void persist() {
        if (this.isNew()) {
            InfrastructureEntityProjectLocalServiceUtil.addInfrastructureEntityProject(this);
        } else {
            InfrastructureEntityProjectLocalServiceUtil.updateInfrastructureEntityProject(this);
        }
    }
}